version: "3.1"

services:
  redmine:
    image: redmine:3.4
    restart: always
    env_file:
      - .env
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: redmine
    volumes:
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
